name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.22

      - name: Install
        run: bun install

      - name: Build
        run: bun run --filter any-agent build

      - name: Typecheck
        run: bun run --filter any-agent typecheck

      - name: Test
        run: bun run --filter any-agent test
